export const COMPUTED_TYPOGRAPHY_PROPERTIES = [
  "fontFamily",
  "fontSize",
  "fontWeight",
  "fontStyle",
  "lineHeight",
  "letterSpacing",
  "wordSpacing",
  "textIndent",
  "textAlign",
  "color",
  "backgroundColor",
  "textTransform",
  "textDecorationLine",
  "writingMode",
  "verticalAlign",
  "direction",
  "unicodeBidi",
  "whiteSpace",
  "overflowWrap",
  "wordBreak",
  "hyphens",
  "opacity",
  "visibility",
] as const;

export const COMPUTED_LAYOUT_PROPERTIES = [
  "display",
  "width",
  "height",
  "marginTop",
  "marginRight",
  "marginBottom",
  "marginLeft",
  "paddingTop",
  "paddingRight",
  "paddingBottom",
  "paddingLeft",
] as const;

export const SKIP_TAGS = new Set(["script", "style", "noscript", "template", "meta", "link", "head"]);

export const TEXTUAL_TAGS = new Set([
  "p",
  "span",
  "li",
  "td",
  "th",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "blockquote",
  "figcaption",
  "label",
  "a",
  "em",
  "strong",
  "rt",
  "rp",
]);
